/**
 * Benzy certification — offline bundle generator.
 *
 *   npx tsx scripts/benzy-cert-payloads.ts [--out <dir>] [--case <id>] [--date <yyyy-mm-dd>]
 *
 * Runs all 9 documented certification cases through the REAL client code in
 * src/lib/benzy-booking.ts, with the network replaced by the reference transport
 * in ./benzy-cert-reference.ts. Every call is captured and written as its own
 * JSON file:
 *
 *   benzy-cert-output/<id>.<case name>/1.Signature.json … 15.RetrieveBooking.json
 *
 * Request bodies are exactly what the integration transmits. Responses are
 * reference-shaped (Benzy staging only answers whitelisted IPs) — swap them for
 * live captures by running POST /api/benzy/cert-run { caseId, write: true } once
 * the whitelist is in place.
 */
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

/* ---- args ---- */

const argv = process.argv.slice(2);
const arg = (flag: string) => {
  const i = argv.indexOf(flag);
  return i >= 0 ? argv[i + 1] : undefined;
};
const outDir = resolve(ROOT, arg("--out") || "benzy-cert-output");
const onlyCase = arg("--case") ? Number(arg("--case")) : undefined;
const today = arg("--date") ? new Date(`${arg("--date")}T00:00:00Z`) : new Date();

/* ---- env (cfg in benzy-booking is read at import time, so load .env first) ---- */

async function loadEnv() {
  let raw = "";
  try {
    raw = await readFile(join(ROOT, ".env"), "utf8");
  } catch {
    console.warn("[cert] no .env found — Signature payload will show empty credentials");
    return;
  }
  for (const line of raw.split("\n")) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)$/);
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2].trim().replace(/^["']|["']$/g, "");
  }
}

const NOTE =
  "Request body is generated by the TouristLeader integration (src/lib/benzy-booking.ts) and is what we transmit. " +
  "Response is reference-shaped, not a live capture — Benzy staging answers whitelisted IPs only; live responses " +
  "will replace these on the certification run.";

async function main() {
  await loadEnv();

  const { CERT_CASES, generateCertBundle } = await import("../src/lib/benzy-cert-cases.ts");
  const { installReferenceTransport } = await import("./benzy-cert-reference.ts");

  const cases = onlyCase ? CERT_CASES.filter((c) => c.id === onlyCase) : CERT_CASES;
  if (!cases.length) throw new Error(`Unknown case id ${onlyCase}`);

  await rm(outDir, { recursive: true, force: true });
  await mkdir(outDir, { recursive: true });

  const manifest: Record<string, unknown>[] = [];

  for (const c of cases) {
    const restore = installReferenceTransport({ id: c.id, name: c.name, tripType: c.tripType, routing: c.routing, baggage: c.baggage }, today);
    try {
      const bundle = await generateCertBundle(c, today, { note: NOTE });
      const dir = join(outDir, `${c.id}.${c.name}`);
      await mkdir(dir, { recursive: true });
      for (const f of bundle.files) await writeFile(join(dir, f.filename), f.content, "utf8");

      const search = bundle.files.find((f) => f.doc.operation === "ExpressSearch")?.doc.request as
        | { Trips?: { OnwardDate?: string; ReturnDate?: string }[] }
        | undefined;

      manifest.push({
        case: c.id,
        name: c.name,
        tripType: c.tripType,
        routing: c.routing,
        baggage: c.baggage,
        onwardDate: search?.Trips?.[0]?.OnwardDate,
        returnDate: search?.Trips?.[0]?.ReturnDate || null,
        passengers: "2 ADT · 2 CHD · 2 INF",
        transactionId: bundle.result.transactionId,
        pnrs: bundle.result.pnrs,
        netAmount: bundle.result.netAmount,
        ssrAmount: bundle.result.ssrAmount,
        files: bundle.files.map((f) => f.filename),
      });

      console.log(`case ${c.id}: ${bundle.files.length} files → ${dir.replace(`${ROOT}/`, "")}`);
    } finally {
      restore();
    }
  }

  await writeFile(
    join(outDir, "manifest.json"),
    `${JSON.stringify(
      {
        provider: "Benzy Infotech (Akbar Travels B2B)",
        environment: "staging · bitest",
        generatedAt: new Date().toISOString(),
        note: NOTE,
        cases: manifest,
      },
      null,
      2,
    )}\n`,
    "utf8",
  );

  await writeFile(join(outDir, "README.txt"), readme(manifest.length), "utf8");
  console.log(`\nmanifest + README → ${outDir.replace(`${ROOT}/`, "")}`);
}

function readme(caseCount: number): string {
  return [
    "TouristLeader × Benzy Flight API — certification call bundle",
    "==========================================================",
    "",
    `${caseCount} test case folder(s). Each folder holds ONE JSON file per API call, numbered in`,
    "call order — 1.Signature.json through 15.RetrieveBooking.json.",
    "",
    "Each file is a standalone JSON document:",
    "",
    "  step       call number within the flow",
    "  operation  Benzy operation name",
    "  method     always POST",
    "  url        full endpoint URL",
    "  endpoint   path only",
    "  timestamp  when the call was made (ISO)",
    "  headers    headers as transmitted (Bearer JWT truncated)",
    "  request    request body",
    "  response   response body",
    "",
    "Call order",
    "----------",
    "  1  Signature            authenticate → Bearer token + encrypted ClientID",
    "  2  ExpressSearch        start async search → master TUI",
    "  3  WebSettings          per-airline capability flags",
    "  4  GetExpSearch         poll until Completed=True → journeys with Index",
    "  5  SSR                  ancillary catalogue for the chosen journey(s)",
    "  6  SmartPricer          re-price selection → repriced TUI",
    "  7  GetSPricer           poll for the confirmed fare",
    "  8  GetTravelCheckList   mandatory passenger fields",
    "  9  CreateItinerary      create booking → TransactionID",
    " 10  StartPay (HB)        hold from agent deposit wallet",
    " 11  GetItineraryStatus   poll hold status",
    " 12  RetrieveBooking      held booking + airline PNR",
    " 13  StartPay (HP)        purchase / ticket",
    " 14  GetItineraryStatus   poll ticketing status",
    " 15  RetrieveBooking      final ticketed booking",
    "",
    "Chained values: TUI (search→price→book) · Index (chosen flight) ·",
    "TransactionID (booking id) · Airline PNR (final).",
    "",
    "Status",
    "------",
    "Request bodies are produced by the live TouristLeader integration code and are",
    "exactly what we transmit. Response bodies are reference-shaped: Benzy staging",
    "accepts whitelisted IPs only, so responses could not be captured live yet.",
    "Once our IP is whitelisted the same files regenerate with real responses via",
    "POST /api/benzy/cert-run { caseId, write: true }.",
    "",
  ].join("\n");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
